### ISSUE TITLE
 Frameworks detected: Android framework is detected in the project Configure

### ISSUE THREAD

**Issue by ahmetoguzer** [norips/Projet_MBA#4]
Hi, I'm getting this error "Frameworks detected: Android framework is detected in the project Configure" when I open the application

**Comment by norips** [comment]
Hi, you need to open both folder, aka, do not open ARMuseum folder but the root folder

**Comment by ahmetoguzer** [comment]
I downloaded the whole project and tried again and again I get the same error.I needed different video playback for different nft.I can not identify the markers in the sdk ARmovie example.I think you made the marker definition at Armuseum project.I would appreciate if you help me on this.Thanks..

**Comment by norips** [comment]
Open the project like in the image above.
Just open the ARMuseumProj folder.
![capture du 2017-01-26 16-45-40](https://cloud.githubusercontent.com/assets/7265548/22340741/c262ef94-e3ee-11e6-9615-67754bd3c6e2.png)

**Comment by islammustafaeg** [comment]
This project not build from Android Studio.

you need to import the project files.

In Android Studio

File >>>> New >>>>> Import Project

hope this resolve your issues
