### ISSUE TITLE
Didn't Work

### ISSUE THREAD

**Issue by ShahriarVelayat** [norips/Projet_MBA#7]
Hi 
in the first thanks to your project
I'm new to Artoolkit
I had downloaded your project and run it on two devices but it doesn't work with any pictures.
Can you help me?
it has no error in downloading json file and targets everything is ok :(
thanks

**Comment by norips** [comment]
Hi 😄 , thanks for the interest in my project do you see the endpoint as shown in the first screen in the demo video ? Can you try to connect your smartphone to your computer and show the log relatives to the app ? In a pastebin for example.

Regards

**Comment by ShahriarVelayat** [comment]
[you can see log here](http://gshub.ir/ScreenRecords/Log.txt)
and 
[ScreenRecord here](http://gshub.ir/ScreenRecords/SCR_20170911_211906.mp4)
thanks

**Comment by norips** [comment]
Thanks for the informations, can you try using "test oo mba" (last configuration), and use this painting as marker :
[Sainte Famille avec sainte Dorothée](http://www.musba-bordeaux.fr/fr/article/jnegretti) (click on the picture on the right of the page)
[Portrait d’homme tenant une lettre et un gant](http://www.musba-bordeaux.fr/fr/article/Veronese)
